<?php


namespace App\Helpers;


class ListHelper
{

    public static function wardsList()
    {
        $wardsList=[
            "TANDALE",
            "HANANASIF",
            "MWANANYAMALA",
            "MAKUMBUSHO",
            "KIJITONYAMA",
            "KINONDONI",
            "MAGOMENI",
            "MZIMUNI",
            "KIGOGO",
            "NDUGUMBI",
            "KAWE",
            "MAKONGO",
            "MBEZI JUU",
            "KUNDUCHI",
            "WAZO",
            "BUNJU",
            "MABWEPANDE",
            "MBWENI",
            "MIKOCHENI",
            "MSASANI",
        ];
        return $wardsList;
    }

    public static function subWardsList()
    {
        $subWardsList = [
            "MTOGOLE",
            "MUHALITANI",
            "SOKONI",
            "PAKACHA",
            "KWA TUMBO",
            "MKUNDUGE",
            "HANANASIF",
            "MKUNGUNI  B",
            "KAWAWA",
            "MKUNGUNI A",
            "KISUTU",
            "BWAWANI",
            "MSISIRI  B",
            "KAMBANGWA",
            "MSOLOMI",
            "MWINYIJUMA",
            "MSISIRI  A",
            "KWA KOPA",
            "MAKUMBUSHO",
            "MCHANGANI",
            "MBUYUNI",
            "MINAZINI",
            "KISIWANI",
            "SINGANO",
            "MPAKANI A",
            "MWENGE",
            "NZASA",
            "KIJITONYAMA",
            "MPAKANI  B",
            "BWAWANI",
            "ALIMAUA   A",
            "ALIMAUA  B",
            "KUMBUKUMBU",
            "SHAMBA",
            "ADA ESTATE",
            "KINONDONI MJINI",
            "MAKUTI  A",
            "MAKUTI  B",
            "SUNA",
            "DOSSI",
            "IDRISA",
            "MWINYI MKUU",
            "IDRISA",
            "MAKUMBUSHO",
            "MTAMBANI",
            "MKWAJUNI",
            "KIGOGO KATI",
            "MTAA WA MBUYUNI",
            "MPAKANI",
            "KAGERA MIKOROSHINI",
            "MAKANYA",
            "VIGAENI",
            "UKWAMANI",
            "MBEZI BEACH  A",
            "MZIMUNI",
            "MBEZI BEACH  B",
            "MAKONGO JUU",
            "CHANGANYIKENI",
            "MLALAKUWA",
            "MBUYUNI",
            "MBEZI JUU",
            "MBEZI MTONI",
            "MBEZI JOGOO",
            "MBEZI KATI",
            "MBEZI NDUMBWI",
            "TEGETA",
            "MTONGANI",
            "KONDO",
            "UNUNIO",
            "KILONGAWIMA",
            "PWANI",
            "WAZO",
            "MADALE",
            "SALASALA",
            "MIVUMONI",
            "KILIMAHEWA",
            "KILIMAHEWA JUU",
            "NYAKASANGWE",
            "KISANGA",
            "DOVYO",
            "BASIHAYA",
            "MKOANI",
            "KILUNGULE",
            "BOKO",
            "BUNJU  A",
            "KIHONZILE",
            "BUNJU  B",
            "MABWEPANDE",
            "MJI MPYA",
            "MBOPO",
            "TETA",
            "MAPUTO",
            "MPIJIMBWENI",
            "MALINDI ESTATE",
            "MBWENI",
            "MIKOCHENI  A",
            "MIKOCHENI  B",
            "T.P.D.C",
            "DARAJANI",
            "REGENT ESTATE",
            "ALLY HASSAN MWINYI",
            "OYSTERBAY",
            "MASAKI",
            "MIKOROSHINI",
            "BONDE LA MPUNGA",
            "MAKANGIRA",
          ];
return $subWardsList;
}
}
